services:
    PoP\Highlights\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Highlights\TypeResolverPickers\:
        resource: '../src/TypeResolverPickers/*'
        public: true
